email_controllers:
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '[a-z]{2}'
    resource:
        path: ../src/Internal/Controller/
        namespace: Module\Email\Internal\Controller
