framework:
    cache:
        app: cache.adapter.redis_tag_aware
        default_redis_provider: '%env(REDIS_URL)%'
        system: cache.adapter.system

        pools:
            cache.cms_page_cache:
                adapter: cache.adapter.redis_tag_aware
                default_lifetime: 86400
