sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        enable_logs: true
        ignore_exceptions:
            - 'Symfony\Component\ErrorHandler\Error\FatalError'
            - 'Symfony\Component\Debug\Exception\FatalErrorException'
            - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
        traces_sample_rate: 1.0
    register_error_listener: true
    register_error_handler: false

