sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        ignore_exceptions:
            - 'Symfony\Component\ErrorHandler\Error\FatalError'
            - 'Symfony\Component\Debug\Exception\FatalErrorException'
            - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
        traces_sample_rate: 1.0
    register_error_listener: true
    register_error_handler: false
    tracing:
        dbal:
            enabled: true
        twig:
            enabled: true
        cache:
            enabled: true
        http_client:
            enabled: true

monolog:
    handlers:
        sentry_logs:
            type: service
            id: Sentry\SentryBundle\Monolog\LogsHandler
