services:
    _defaults:
        autowire: true
        autoconfigure: true

    Module\Ballot\Tests\Stub\:
        resource: '../tests/Stub/'
        public: true

    Module\Ballot\Internal\BallotService: { public: true }
    Module\Ballot\Internal\Cron\SettleDueBallotsCron: { public: true }
    Module\Ballot\Internal\Notification\OpenBallotNotificationProvider: { public: true }
    Module\Ballot\Contract\BallotInterface:
        alias: Module\Ballot\Internal\BallotService
        public: true
