services:
    _defaults:
        autowire: true
        autoconfigure: true

    Module\Ballot\:
        resource: '../src/'
        exclude:
            - '../src/Internal/Entity/'

    Module\Ballot\Contract\BallotInterface: '@Module\Ballot\Internal\BallotService'
