controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix: /{_locale}

api:
    resource: ../src/Controller/ApiController.php
    type: attribute