controllers:
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '[a-z]{2}'
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    exclude: ../src/Controller/NonLocale/

frontpage:
    type: attribute
    resource: ../src/Controller/NonLocale/FrontpageController.php

sitemap:
    type: attribute
    resource: ../src/Controller/NonLocale/SitemapController.php

api:
    type: attribute
    resource: ../src/Controller/NonLocale/ApiController.php

ajax:
    type: attribute
    resource: ../src/Controller/NonLocale/AjaxController.php

api_auth:
    type: attribute
    resource: ../src/Controller/NonLocale/AuthApiController.php

api_cms:
    type: attribute
    resource: ../src/Controller/NonLocale/CmsCrudApiController.php

api_logs:
    type: attribute
    resource: ../src/Controller/NonLocale/LogsApiController.php
