controllers:
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '[a-z]{2}'
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    exclude: ../src/Controller/NonLocale/

api:
    type: attribute
    resource:
        path: ../src/Controller/NonLocale/Api/
        namespace: App\Controller\NonLocale\Api

frontpage:
    type: attribute
    resource: ../src/Controller/NonLocale/FrontpageController.php

ajax:
    type: attribute
    resource: ../src/Controller/NonLocale/AjaxController.php

robots:
    type: attribute
    resource: ../src/Controller/NonLocale/RobotsController.php

sitemap:
    type: attribute
    resource: ../src/Controller/NonLocale/SitemapController.php
