controllers:
    type: attribute
    prefix: /{_locale}
    resource:
        path: ../src/Controller/
        namespace: App\Controller

frontpage:
    type: attribute
    resource: ../src/Controller/NonLocale/FrontpageController.php

api:
    type: attribute
    resource: ../src/Controller/NonLocale/ApiController.php

ajax:
    type: attribute
    resource: ../src/Controller/NonLocale/AjaxController.php
